# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: MysqlDeploymentOnMachineGroup@1
  inputs:
    TaskNameSelector: 'InlineSqlTask'
    SqlInline: |
      CREATE DATABASE IF NOT EXISTS gamedb;
      use gamedb
      CREATE TABLE `gametable` (
        `id` int NOT NULL,
        `name` varchar(45) NOT NULL,
        `platform` varchar(45) NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `id_UNIQUE` (`id`)
      )
    ServerName: 'localhost'
    DatabaseName: 'gamedb'
    SqlUsername: 'root'
    SqlPassword: 'root'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
